version: "3.9"

services:
  app:
    image: survey-app:latest
    container_name: survey_app
    build:
      context: .
    ports:
      - "9999:9999"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/survey_db?stringtype=unspecified
      SPRING_DATASOURCE_USERNAME: argen
      SPRING_DATASOURCE_PASSWORD: coolboy
      JWT_SECRET: 984hg493gh0439rthr9uruj2fda309yh937gc763fe87t3f89723gf
      JWT_LIFETIME: 25m
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    container_name: survey_db
    ports:
      - "5050:5432"
    environment:
      POSTGRES_DB: survey_db
      POSTGRES_USER: argen
      POSTGRES_PASSWORD: coolboy
    volumes:
      - db-data:/var/lib/postgresql/data #

volumes:
  db-data: