server:
  port: 9999
  address: 0.0.0.0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5050/survey_db?stringtype=unspecified
    username: argen
    password: coolboy
    driver-class-name: org.postgresql.Driver

jwt:
  secret: 984hg493gh0439rthr9uruj2fda309yh937gc763fe87t3f89723gf
  lifetime: 25m
